BEGIN;
SELECT plan(19);
CREATE TEMP TABLE tap_runs(msg text);
CREATE TEMP TABLE op_vars(name text,id uuid,payload jsonb);
GRANT ALL ON tap_runs,op_vars TO authenticated;
INSERT INTO auth.users(id,aud,role,email,email_confirmed_at) VALUES
('a3500000-0000-0000-0000-000000000001','authenticated','authenticated','a3.receipt.owner@example.test',now());
INSERT INTO op_vars SELECT 'ws',id,NULL FROM public.workspaces WHERE owner_id='a3500000-0000-0000-0000-000000000001';
WITH a AS(INSERT INTO public.accounts(workspace_id,name,type,initial_balance,current_balance) SELECT id,'Receipt bank','cash',1000,1000 FROM op_vars WHERE name='ws' RETURNING id) INSERT INTO op_vars SELECT 'account',id,NULL FROM a;
SET LOCAL request.jwt.claim.sub='a3500000-0000-0000-0000-000000000001';
SET LOCAL role='authenticated';
INSERT INTO op_vars VALUES('tx',public.fn_create_transaction_with_splits((SELECT id FROM op_vars WHERE name='ws'),'Receipt expense',100),NULL);
INSERT INTO op_vars SELECT 'pay',NULL,jsonb_build_object('p_workspace_id',(SELECT id FROM op_vars WHERE name='ws'),'p_account_id',(SELECT id FROM op_vars WHERE name='account'),'p_transaction_id',(SELECT id FROM op_vars WHERE name='tx'),'p_amount',30,'p_payment_date','2050-10-01','p_affects_balance',true);
UPDATE op_vars SET id=public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_record_payment','payment-1',payload) WHERE name='pay';
INSERT INTO tap_runs SELECT is((SELECT current_balance FROM public.accounts WHERE id=(SELECT id FROM op_vars WHERE name='account')),970::numeric,'First payment debits once');
INSERT INTO tap_runs SELECT is(public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_record_payment','payment-1',(SELECT payload FROM op_vars WHERE name='pay')),(SELECT id FROM op_vars WHERE name='pay'),'Retry returns original payment');
INSERT INTO tap_runs SELECT is((SELECT count(*)::int FROM public.payments WHERE transaction_id=(SELECT id FROM op_vars WHERE name='tx')),1,'Retry does not create another payment');
INSERT INTO tap_runs SELECT is((SELECT current_balance FROM public.accounts WHERE id=(SELECT id FROM op_vars WHERE name='account')),970::numeric,'Retry does not debit twice');
INSERT INTO tap_runs SELECT throws_ok($q$SELECT public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_record_payment','payment-1',jsonb_set((SELECT payload FROM op_vars WHERE name='pay'),'{p_amount}','40'))$q$,'P0001',NULL,'Conflicting retry rejected');
SELECT public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_record_payment','payment-2',(SELECT payload FROM op_vars WHERE name='pay'));
INSERT INTO tap_runs SELECT is((SELECT current_balance FROM public.accounts WHERE id=(SELECT id FROM op_vars WHERE name='account')),940::numeric,'Same amount with new intent remains legitimate');
INSERT INTO tap_runs SELECT ok((SELECT operation_key='payment-1' FROM public.payments WHERE id=(SELECT id FROM op_vars WHERE name='pay')),'Receipt key survives snapshot/reload');
INSERT INTO op_vars SELECT 'purchase',NULL,jsonb_build_object('p_workspace_id',(SELECT id FROM op_vars WHERE name='ws'),'p_description','Receipt purchase','p_total_amount',120,'p_installment_count',3,'p_purchase_date','2050-10-01');
UPDATE op_vars SET id=public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_create_purchase_with_splits','purchase-1',payload) WHERE name='purchase';
INSERT INTO tap_runs SELECT is(public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_create_purchase_with_splits','purchase-1',(SELECT payload FROM op_vars WHERE name='purchase')),(SELECT id FROM op_vars WHERE name='purchase'),'Retry returns original purchase');
INSERT INTO tap_runs SELECT is((SELECT count(*)::int FROM public.installments WHERE purchase_id=(SELECT id FROM op_vars WHERE name='purchase')),3,'Purchase retry keeps only three installments');
INSERT INTO tap_runs SELECT throws_ok($q$SELECT public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_record_payment','invalid',jsonb_set((SELECT payload FROM op_vars WHERE name='pay'),'{p_amount}','"NaN"'))$q$,'P0001',NULL,'Invalid write rolls back receipt');
INSERT INTO tap_runs SELECT is((SELECT count(*)::int FROM public.financial_operations WHERE operation_key='invalid'),0,'Failed attempt leaves no receipt');
INSERT INTO tap_runs SELECT throws_ok($q$SELECT public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_add_workspace_member','unauthorized',(SELECT payload FROM op_vars WHERE name='pay'))$q$,'P0001',NULL,'Non-whitelisted routine denied');
INSERT INTO tap_runs SELECT throws_ok($q$SELECT public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_record_payment','extra',(SELECT payload FROM op_vars WHERE name='pay')||'{"p_created_by":"spoof"}')$q$,'P0001',NULL,'Unknown payload field denied');
INSERT INTO tap_runs SELECT ok(NOT has_table_privilege('authenticated','public.financial_operations','INSERT'),'Receipt journal cannot be inserted directly');
INSERT INTO tap_runs SELECT ok(NOT has_table_privilege('authenticated','public.financial_operations','TRUNCATE'),'Receipt journal cannot be truncated');
INSERT INTO tap_runs SELECT ok(NOT has_function_privilege('anon','public.fn_execute_financial_operation(uuid,text,text,jsonb)','EXECUTE'),'Anonymous cannot execute');
SELECT public.fn_delete_transaction((SELECT id FROM op_vars WHERE name='ws'),(SELECT id FROM op_vars WHERE name='tx'));
INSERT INTO tap_runs SELECT is(public.fn_execute_financial_operation((SELECT id FROM op_vars WHERE name='ws'),'fn_record_payment','payment-1',(SELECT payload FROM op_vars WHERE name='pay')),(SELECT id FROM op_vars WHERE name='pay'),'Deleted result remains a tombstone');
INSERT INTO tap_runs SELECT is((SELECT current_balance FROM public.accounts WHERE id=(SELECT id FROM op_vars WHERE name='account')),1000::numeric,'Replay after deletion cannot charge again');
INSERT INTO tap_runs SELECT is((SELECT count(*)::int FROM public.payments WHERE transaction_id=(SELECT id FROM op_vars WHERE name='tx')),0,'Replay cannot recreate a deleted payment');
RESET ROLE;
SELECT (SELECT array_agg(msg) FROM tap_runs WHERE msg LIKE 'not ok%') AS not_ok_messages,
 extensions._get('curr_test')::int AS ran,extensions._get('plan')::int AS planned,extensions.num_failed()::int AS failed,ARRAY(SELECT * FROM extensions.finish()) AS finish_diagnostics;
ROLLBACK;
